# =============================================================================
#  ENVIRONMENT VARIABLES — ULTIMATE MODE (AsusMuxDgpu)
#  Setup: RTX 3050 6GB | nvidia-open-dkms 590 | linux-g14
#  Última revisión: Marzo 2026
# =============================================================================

# --- XDG ---
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# --- TOOLKIT BACKENDS ---
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct

env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = CLUTTER_BACKEND,wayland

env = GDK_DISABLE_SCHEDULER,1 
env = ANV_VIDEO_DECODE,1

# --- CURSOR ---
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# --- NVIDIA CORE (ULTIMATE — RTX maneja todo) ---
env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm

# --- SDL / GAMING ---
env = SDL_VIDEODRIVER,wayland,x11

# --- ELECTRON / CEF ---
env = ELECTRON_OZONE_PLATFORM_HINT,auto

# --- GAMING ---
env = __GL_THREADED_OPTIMIZATIONS,1
env = __GL_MAX_FRAMES_ALLOWED,1
env = __GL_YIELD,NOTHING

# --- NUNCA ACTIVAR ---
# env = AQ_NO_MODIFIERS,1      <- freeze confirmado
# env = NVD_BACKEND,direct     <- freeze confirmado
# env = __NV_DISABLE_EXPLICIT_SYNC,1  <- crashea hyprlock
