general {
    # Esto asegura que el sistema sepa qué comando usar para bloquear
    lock_cmd = ~/.config/hyprlock/lock.sh      
    before_sleep_cmd = loginctl lock-session    
    after_sleep_cmd = hyprctl dispatch dpms on  
}

# 1. AVISO VISUAL (2.5 min)
# Baja el brillo al 10% para avisarte que se va a bloquear pronto
listener {
    timeout = 150                                
    on-timeout = brightnessctl -s set 10         # Guarda brillo actual y baja al 10%
    on-resume = brightnessctl -r                 # Restaura brillo anterior al mover mouse
}

listener {
    timeout = 300                                
    on-timeout = loginctl lock-session           
}

# 3. APAGAR PANTALLA (5.5 min)
# Ahorra energía apagando el monitor
listener {
    timeout = 330                                
    on-timeout = hyprctl dispatch dpms off       
    on-resume = hyprctl dispatch dpms on         
}

# 4. SUSPENDER PC (30 min)
# Solo si realmente la dejaste abandonada
listener {
    timeout = 1800                               
    on-timeout = systemctl suspend               
}
