ipc = on
splash = false

# 1. Precubar la imagen (Cargarla en memoria RAM)
preload = /home/moonly/Wallpapers/kafka.jpeg

# 2. Asignarla a TU monitor (El truco es usar la coma inicial para decir "todos")
wallpaper = ,/home/moonly/Wallpapers/kafka.jpeg
