source = /home/moonly/.config/hypr/autostart.conf
source = /home/moonly/.config/hypr/environment.conf
source = /home/moonly/.config/hypr/keybindings.conf
source = /home/moonly/.config/hypr/keyboard.conf
source = /home/moonly/.config/hypr/monitor.conf
source = /home/moonly/.config/hypr/style.conf
source = /home/moonly/.config/hypr/windowrules.conf

debug {
    disable_logs = false
}